<a href="https://colab.research.google.com/github/hoonzi-s/PyData/blob/main/Ch05.%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
from pandas import Series, DataFrame

#**5.1** Pandas 자료구조 소개

##**5.1.1** Series

In [48]:
obj = pd.Series([4, 7, -5, -3])
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [49]:
obj.values

array([ 4,  7, -5, -3])

In [50]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [51]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'c', 'a'])
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [52]:
obj2.index

Index(['d', 'b', 'c', 'a'], dtype='object')

In [53]:
obj2['a']

3

In [54]:
obj2['d'] = 6
obj2

d    6
b    7
c   -5
a    3
dtype: int64

In [55]:
obj2[['c', 'a', 'd']]

c   -5
a    3
d    6
dtype: int64

In [56]:
obj2 * 2

d    12
b    14
c   -10
a     6
dtype: int64

In [57]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
c       0.006738
a      20.085537
dtype: float64

In [58]:
'b' in obj2

True

In [59]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 =  pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [60]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [61]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [62]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [63]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [64]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [65]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [66]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [67]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [68]:
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [69]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan    -3
dtype: int64

##**5.1.2** DataFrame

In [70]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [71]:
frame.head()  # 처음 5개 행

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [72]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])  # 원하는 순서대로 칼럼 지정

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [73]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [74]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [75]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [76]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [77]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [78]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [79]:
frame2['debt'] = np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [80]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [81]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [82]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [83]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3      

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [84]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [85]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [86]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [87]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

##**5.1.3** Index

In [88]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [89]:
index[1:]

Index(['b', 'c'], dtype='object')

In [90]:
# index는 변경이 불가능
index[1] = 'd'

TypeError: ignored

In [91]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [92]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [93]:
obj2.index is labels

True

In [94]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [95]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [96]:
'Ohio' in frame3.columns

True

In [97]:
2003 in frame3.index

False

#**5.2** 핵심 기능

##**5.2.1** Reindex

In [98]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [99]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [100]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [101]:
obj3.reindex(np.arange(6), method = 'ffill')    # 값이 없으면 직전 값으로 채워넣음 (forward fill?)

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [102]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                     index = ['a', 'c', 'd'], 
                     columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [103]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [104]:
states = ['Texas', 'Utah', 'California']
frame3 = frame.reindex(columns = states)
frame3

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [105]:
frame3.loc[['d', 'c', 'a'], states]

Texas  Utah  California
d      7   NaN           8
c      4   NaN           5
a      1   NaN           2

##**5.2.2** 하나의 로우나 칼럼 삭제하기

In [106]:
obj = pd.Series(np.arange(5), index = ['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [107]:
new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [108]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int64

In [109]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [111]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [112]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [113]:
obj.drop('c', inplace = True)
obj

a    0
b    1
d    3
e    4
dtype: int64

##**5.2.3** Indexing, Selection, and Filtering

In [114]:
obj = pd.Series(np.arange(4), index = ['a', 'b', 'c', 'd'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [115]:
obj['b']

1

In [116]:
obj[1]

1

In [117]:
obj[2:7]

c    2
d    3
dtype: int64

In [118]:
obj[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: int64

In [119]:
obj[[1, 3]]

b    1
d    3
dtype: int64

In [120]:
obj[obj < 2]

a    0
b    1
dtype: int64

In [121]:
obj['b':'c']

b    1
c    2
dtype: int64

In [122]:
obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: int64

In [123]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [124]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [125]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [126]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [128]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### loc과 iloc으로 선택하기

In [129]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [130]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [131]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [132]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [133]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

##**5.2.4** 정수 색인

In [134]:
ser = pd.Series(np.arange(3))
ser

0    0
1    1
2    2
dtype: int64

In [135]:
ser2 = pd.Series(np.arange(3), index = ['a', 'b', 'c'])
ser2

a    0
b    1
c    2
dtype: int64

In [136]:
ser2[-1]

2

In [137]:
ser[:1]

0    0
dtype: int64

In [138]:
ser.loc[:1]

0    0
1    1
dtype: int64

In [139]:
ser.iloc[:1]

0    0
dtype: int64

##**5.2.5** 산술 연산과 데이터 정렬

In [140]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [141]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [142]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [143]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [144]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [145]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### 산술 연산 메소드에 채워 넣을 값 지정하기

In [146]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [147]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [148]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [149]:
df1 + df2


a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [150]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [151]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [152]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [153]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame과 Series 간의 연산

In [154]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
arr[0]

array([0, 1, 2, 3])

In [156]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [157]:
frame = pd.DataFrame(np.arange(12).reshape(4, 3),
                     columns = list('bde'),
                     index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [158]:
series = frame.iloc[0]
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [159]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [160]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [161]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [162]:
series3 = frame['d']
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [163]:
frame.sub(series3, axis = 'index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

##**5.2.6** 함수 적용과 매핑

In [164]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.354733  0.452631  1.780632
Ohio   -0.988939 -0.493915 -0.164006
Texas  -0.997793 -1.159574 -0.554319
Oregon  1.537261  1.540230  0.282230

In [165]:
np.abs(frame)

b         d         e
Utah    0.354733  0.452631  1.780632
Ohio    0.988939  0.493915  0.164006
Texas   0.997793  1.159574  0.554319
Oregon  1.537261  1.540230  0.282230

In [166]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.535054
d    2.699805
e    2.334951
dtype: float64

In [167]:
frame.apply(f, axis = 'columns')

Utah      2.135365
Ohio      0.824933
Texas     0.605256
Oregon    1.258000
dtype: float64

In [168]:
frame.apply(f)

b    2.535054
d    2.699805
e    2.334951
dtype: float64

In [169]:
def f(x):
  return pd.Series([x.min(), x.max()], index = ['min', 'max'])

frame.apply(f)

b         d         e
min -0.997793 -1.159574 -0.554319
max  1.537261  1.540230  1.780632

In [170]:
format = lambda x: '%.2f' %x
frame.applymap(format)

b      d      e
Utah    -0.35   0.45   1.78
Ohio    -0.99  -0.49  -0.16
Texas   -1.00  -1.16  -0.55
Oregon   1.54   1.54   0.28

In [171]:
frame['e'].map(format)

Utah       1.78
Ohio      -0.16
Texas     -0.55
Oregon     0.28
Name: e, dtype: object

##**5.2.7** 정렬과 순위

In [172]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [173]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [174]:
frame = pd.DataFrame(np.arange(8).reshape(2, 4),
                     index = ['three', 'one'],
                     columns = ['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [175]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [176]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [177]:
obj = pd.Series([4, 8, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    8
dtype: int64

In [178]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [179]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [180]:
frame.sort_values(by = 'b', ascending = False)

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [181]:
frame.sort_values(by = ['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [182]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [183]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [184]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [185]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [186]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [187]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

##**5.2.8** 중복 색인

In [188]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [189]:
obj.index.is_unique

False

In [190]:
obj['a']

a    0
a    1
dtype: int64

In [191]:
obj['c']

4

In [192]:
df = pd.DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])
df

0         1         2
a -0.971199  0.746787 -1.115855
a  0.443976  1.178134 -2.397119
b -0.293732  1.505406  0.432540
b  0.938424 -1.344805 -0.844039

In [193]:
df.loc['b']

0         1         2
b -0.293732  1.505406  0.432540
b  0.938424 -1.344805 -0.844039

#**5.3** 기술 통계 계산과 요약

In [194]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [195]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [196]:
df.sum(axis = 0)

one    9.25
two   -5.80
dtype: float64

In [197]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [198]:
df.idxmax()

one    b
two    d
dtype: object

In [199]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [200]:
df.cumsum(axis = 1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [201]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [202]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

##**5.3.1** 상관관계와 공분산

In [259]:
import pandas as pd
import pandas_datareader.data as pdr
import datetime as dt

In [272]:
start = '2022-01-01'
end = '2022-04-25'

df = {ticker: pdr.DataReader(ticker, 'naver', start = '2022-01-01', end = '2022-04-25') for ticker in ['005930', '005935', '010955']}
df

{'005930':              Open   High    Low  Close    Volume
 Date                                            
 2022-01-03  79400  79800  78200  78600  13502112
 2022-01-04  78800  79200  78300  78700  12427416
 2022-01-05  78800  79000  76400  77400  25470640
 2022-01-06  76700  77600  76600  76900  12931954
 2022-01-07  78100  78400  77400  78300  15163757
 ...           ...    ...    ...    ...       ...
 2022-04-19  67100  68000  67000  67300  12959434
 2022-04-20  67000  67400  66500  67400  16693293
 2022-04-21  67600  68300  67500  67700  12847448
 2022-04-22  67200  67300  66700  67000  11791478
 2022-04-25  66500  66700  66300  66300  11016474
 
 [76 rows x 5 columns],
 '005935':              Open   High    Low  Close   Volume
 Date                                           
 2022-01-03  71800  71800  71300  71400   832097
 2022-01-04  71700  71800  71300  71700   590520
 2022-01-05  71900  71900  70500  71400  1538405
 2022-01-06  70500  70900  70300  70900   953399
 2022-01-0

In [292]:
price = pd.DataFrame({ticker: data['Close'].astype(int) for ticker, data in df.items()})
volume = pd.DataFrame({ticker: data['Volume'].astype(int) for ticker, data in df.items()})
volume.dtypes

005930    int64
005935    int64
010955    int64
dtype: object

In [300]:
returns = price.pct_change()
returns.tail()

005930    005935    010955
Date                                    
2022-04-19  0.008996  0.011609 -0.014754
2022-04-20  0.001486 -0.011475  0.003328
2022-04-21  0.004451  0.004975  0.008292
2022-04-22 -0.010340 -0.003300  0.008224
2022-04-25 -0.010448 -0.014901 -0.009788

In [302]:
returns['005930'].corr(returns['005935'])

0.7489894305517294

In [303]:
returns['005930'].cov(returns['005935'])

8.576032976223539e-05

In [297]:
price.pct_change(periods = 2)

005930    005935    010955
Date                                    
2022-01-03       NaN       NaN       NaN
2022-01-04       NaN       NaN       NaN
2022-01-05 -0.015267  0.000000  0.009174
2022-01-06 -0.022872 -0.011158 -0.005425
2022-01-07  0.011628  0.000000  0.021818
...              ...       ...       ...
2022-04-19  0.010511  0.018364 -0.019576
2022-04-20  0.010495  0.000000 -0.011475
2022-04-21  0.005944 -0.006557  0.011647
2022-04-22 -0.005935  0.001658  0.016584
2022-04-25 -0.020679 -0.018152 -0.001645

[76 rows x 3 columns]

In [304]:
returns.corr()

005930    005935    010955
005930  1.000000  0.748989  0.185131
005935  0.748989  1.000000  0.089920
010955  0.185131  0.089920  1.000000

In [305]:
returns.cov()

005930    005935    010955
005930  0.000127  0.000086  0.000033
005935  0.000086  0.000103  0.000015
010955  0.000033  0.000015  0.000257

In [307]:
returns.corrwith(returns['005930'])

005930    1.000000
005935    0.748989
010955    0.185131
dtype: float64

In [308]:
returns.corrwith(volume)

005930   -0.107014
005935   -0.310605
010955    0.324055
dtype: float64

##**5.3.2** 유일값, 값 세기, 멤버

In [309]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'd', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    d
6    b
7    c
8    c
dtype: object

In [310]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [311]:
uniques.sort()

In [312]:
obj.value_counts()

c    3
a    3
d    2
b    1
dtype: int64

In [315]:
pd.value_counts(obj.values, ascending = True)

b    1
d    2
c    3
a    3
dtype: int64

In [316]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [317]:
obj[mask]

0    c
6    b
7    c
8    c
dtype: object

In [318]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [319]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [320]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0