<a href="https://colab.research.google.com/github/hoonzi-s/PyData/blob/main/Ch05.%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from pandas import Series, DataFrame

#**5.1** Pandas 자료구조 소개

##**5.1.1** Series

In [2]:
obj = pd.Series([4, 7, -5, -3])
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5, -3])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'c', 'a'])
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'c', 'a'], dtype='object')

In [8]:
obj2['a']

3

In [9]:
obj2['d'] = 6
obj2

d    6
b    7
c   -5
a    3
dtype: int64

In [10]:
obj2[['c', 'a', 'd']]

c   -5
a    3
d    6
dtype: int64

In [11]:
obj2 * 2

d    12
b    14
c   -10
a     6
dtype: int64

In [13]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
c       0.006738
a      20.085537
dtype: float64

In [14]:
'b' in obj2

True

In [16]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 =  pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [22]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [26]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [27]:
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [28]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan    -3
dtype: int64

##**5.1.2** DataFrame

In [30]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [31]:
frame.head()  # 처음 5개 행

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])  # 원하는 순서대로 칼럼 지정

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [36]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [38]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [39]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [41]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [43]:
frame2['debt'] = np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [44]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [49]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [50]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [52]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3      

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [53]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [54]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [55]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [56]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

##**5.1.3** Index

In [57]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [58]:
index[1:]

Index(['b', 'c'], dtype='object')

In [59]:
# index는 변경이 불가능
index[1] = 'd'

TypeError: ignored

In [60]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [61]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [63]:
obj2.index is labels

True

In [64]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [65]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [66]:
'Ohio' in frame3.columns

True

In [67]:
2003 in frame3.index

False

#**5.2** 핵심 기능

##**5.2.1** Reindex

In [68]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [69]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [70]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [73]:
obj3.reindex(np.arange(6), method = 'ffill')    # 값이 없으면 직전 값으로 채워넣음 (forward fill?)

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [74]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                     index = ['a', 'c', 'd'], 
                     columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [75]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [90]:
states = ['Texas', 'Utah', 'California']
frame3 = frame.reindex(columns = states)
frame3

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [92]:
frame3.loc[['d', 'c', 'a'], states]

Texas  Utah  California
d      7   NaN           8
c      4   NaN           5
a      1   NaN           2

##**5.2.2** 하나의 로우나 칼럼 삭제하기

In [107]:
obj = pd.Series(np.arange(5), index = ['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [95]:
new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [96]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int64

In [97]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [101]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [102]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [108]:
obj.drop('c', inplace = True)
obj

a    0
b    1
d    3
e    4
dtype: int64

##**5.2.3** Indexing, Selection, and Filtering

In [110]:
obj = pd.Series(np.arange(4), index = ['a', 'b', 'c', 'd'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [111]:
obj['b']

1

In [112]:
obj[1]

1

In [114]:
obj[2:7]

c    2
d    3
dtype: int64

In [115]:
obj[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: int64

In [116]:
obj[[1, 3]]

b    1
d    3
dtype: int64

In [117]:
obj[obj < 2]

a    0
b    1
dtype: int64

In [118]:
obj['b':'c']

b    1
c    2
dtype: int64

In [121]:
obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: int64

In [122]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [123]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [124]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [128]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
data < 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [130]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### loc과 iloc으로 선택하기

In [131]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [132]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [133]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [134]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [135]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

##**5.2.4** 정수 색인

In [137]:
ser = pd.Series(np.arange(3))
ser

0    0
1    1
2    2
dtype: int64

In [139]:
ser2 = pd.Series(np.arange(3), index = ['a', 'b', 'c'])
ser2

a    0
b    1
c    2
dtype: int64

In [141]:
ser2[-1]

2

In [142]:
ser[:1]

0    0
dtype: int64

In [143]:
ser.loc[:1]

0    0
1    1
dtype: int64

In [144]:
ser.iloc[:1]

0    0
dtype: int64

##**5.2.5** 산술 연산과 데이터 정렬

In [145]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [146]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [147]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [148]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [149]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [150]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### 산술 연산 메소드에 채워 넣을 값 지정하기

In [152]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [153]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [155]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [156]:
df1 + df2


a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [157]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [158]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [159]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [161]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame과 Series 간의 연산

In [164]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
arr[0]

array([0, 1, 2, 3])

In [166]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [167]:
frame = pd.DataFrame(np.arange(12).reshape(4, 3),
                     columns = list('bde'),
                     index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [169]:
series = frame.iloc[0]
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [172]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [175]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [176]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [179]:
series3 = frame['d']
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [181]:
frame.sub(series3, axis = 'index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

##**5.2.6** 함수 적용과 매핑

In [182]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -3.139581 -1.152693  0.101394
Ohio    0.681076 -0.685167 -0.880804
Texas  -0.825532  0.662305  0.782490
Oregon  2.524319  2.006778  0.098493

In [183]:
np.abs(frame)

b         d         e
Utah    3.139581  1.152693  0.101394
Ohio    0.681076  0.685167  0.880804
Texas   0.825532  0.662305  0.782490
Oregon  2.524319  2.006778  0.098493

In [184]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    5.663900
d    3.159471
e    1.663294
dtype: float64

In [185]:
frame.apply(f, axis = 'columns')

Utah      3.240975
Ohio      1.561880
Texas     1.608021
Oregon    2.425827
dtype: float64

In [187]:
frame.apply(f)

b    5.663900
d    3.159471
e    1.663294
dtype: float64

In [188]:
def f(x):
  return pd.Series([x.min(), x.max()], index = ['min', 'max'])

frame.apply(f)

b         d         e
min -3.139581 -1.152693 -0.880804
max  2.524319  2.006778  0.782490

In [189]:
format = lambda x: '%.2f' %x
frame.applymap(format)

b      d      e
Utah    -3.14  -1.15   0.10
Ohio     0.68  -0.69  -0.88
Texas   -0.83   0.66   0.78
Oregon   2.52   2.01   0.10

In [190]:
frame['e'].map(format)

Utah       0.10
Ohio      -0.88
Texas      0.78
Oregon     0.10
Name: e, dtype: object

##**5.2.7** 정렬과 순위

In [191]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [192]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [195]:
frame = pd.DataFrame(np.arange(8).reshape(2, 4),
                     index = ['three', 'one'],
                     columns = ['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [197]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [198]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [202]:
obj = pd.Series([4, 8, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    8
dtype: int64

In [203]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [204]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [206]:
frame.sort_values(by = 'b', ascending = False)

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [208]:
frame.sort_values(by = ['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [209]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [210]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [211]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [212]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [213]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [214]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

##**5.2.8** 중복 색인

In [216]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [218]:
obj.index.is_unique

False

In [219]:
obj['a']

a    0
a    1
dtype: int64

In [220]:
obj['c']

4

In [221]:
df = pd.DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])
df

0         1         2
a -0.714428 -1.374875  1.678518
a  0.917111  1.157042  0.609637
b  1.521302  0.304002  0.222786
b  0.403376 -0.279005  0.115862

In [222]:
df.loc['b']

0         1         2
b  1.521302  0.304002  0.222786
b  0.403376 -0.279005  0.115862

#**5.3** 기술 통계 계산과 요약

In [224]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [226]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [227]:
df.sum(axis = 0)

one    9.25
two   -5.80
dtype: float64

In [228]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [229]:
df.idxmax()

one    b
two    d
dtype: object

In [230]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [231]:
df.cumsum(axis = 1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [235]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [236]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

##**5.3.1** 상관관계와 공분산

In [246]:
import pandas_datareader.data as pdr
import datetime as pd

In [253]:
start = '2022-01-01'
end = '2022-04-25'

df = web.DataReader('005930', 'naver', start='2019-09-10', end='2019-10-09')
# df = pdr.DataReader('GE', 'yahoo', start='2019-09-10', end='2019-10-09')
# data = pdr.DataReader('GE', 'yahoo', start = start, end = end)
df.head()

Open   High    Low  Close    Volume
Date                                            
2019-09-10  47100  47200  46550  47000   9231792
2019-09-11  47300  47400  46800  47150  16141619
2019-09-16  47000  47100  46400  47100  15550926
2019-09-17  47000  47100  46800  46900   7006280
2019-09-18  46900  47700  46800  47700  10413027

In [242]:
price = pd.D

FileNotFoundError: ignored